#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

rm -rf log.* 0.00* proc*

foamCleanPolyMesh

# Remove surface and features
rm -rf constant/extendedFeatureEdgeMesh

#------------------------------------------------------------------------------
